### ISSUE TITLE
brotli does not work

### ISSUE THREAD

**Issue by patrickmichalina** [tkoenig89/express-static-gzip#24]
Gzip is always on top in the sorted array of compression types.

**Comment by tkoenig89** [comment]
Could you please provide more details, maybe a piece of code or a more detailed description of your scenerio.

And the version of `express-static-gzip` you are using would be appreciated.

**Comment by patrickmichalina** [comment]
Using the latest version, enableBrotli flag does not actually return br encoded files even when Chrome is accepting (gzip, deflate, br). I inspected the code and found `findFirstMatchingCompression` to always return gzip regardless of my brotli setting.

**Comment by tkoenig89** [comment]
I guess you are using 0.3.2, as `findFirstMatchingCompression`, has been replaced in version 1.0.0 (released a few days ago). I added a lot of testing regarding picking the correct encoding. I also found out, that there had been a bug, and compressions have never been picked by order described in the readme.

What the implementation did, and is now doing more accurate in regards to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding), is picking the encoding based on the order and preference of the client and this seems to be the issue here.

As your browser requests 'gzip' first `express-static-gzip` will always serve gzip, when there is a pre compressed gzip file available. So this might not work for your usecase, as it seems to me you would rather make the server decide which encoding to pick.

I could think of adding an additional option to add a 'server-side preference', which will overwrite the clients preference. Something like this maybe?
```
expressStaticGzip('/dir', {
  enableBrotli: true,
  orderPreference: ['br', 'gzip']
});  
```
The name `orderPreference` is maybe not the best choise, and there might be some better way of expressing this.

**Comment by patrickmichalina** [comment]
@tkoenig89 thanks the explanation! 

I didn't realize the order of the client's accept headers was dictating the response... interesting!

I would be very much interested in the `orderPreference` override. I considered forking the repo to achieve this. If you are willing to add it I'd be very grateful.

**Comment by tkoenig89** [comment]
Already taking a look at implementing this :)

I just thought a little more about it and maybe something like `prefere` or `favour` would wourk better.
```
expressStaticGzip('/dir', {
  enableBrotli: true,
  prefere: ['br']
}); 
```

Where `prefere` would take a list of encoding names which will be picked if supported by the client, and all that are not in this array (but registered) would be used in the order the client requests.

-------------
Regarding my decision to take the clients prefered order: I did some research last weekend, and did not really find a lot of information in any standard, which order to pick, so i chose the client's one. But i see your use case is valid, as brotli might make more sense for the server.

**Comment by tkoenig89** [comment]
So... it's implemented i guess :)

I went back to `orderPreference` and added a bunch of tests with your use case to ensure it does as it should. 

Should i push to npm, or would you like to check it out first via git? Would then release version 1.1.0.

**Comment by patrickmichalina** [comment]
I want to send the most compressed version if the client supports it. In this case, the order would be `br, gzip, deflate, etc...`.

**Comment by tkoenig89** [comment]
Should be exactly what i implemented. Checkout version 1.1.0 on npm... published a few seconds ago.

**Comment by patrickmichalina** [comment]
It works! Thanks for all the quick help.

**Comment by charliematters** [comment]
I've just had this same thing on version 2.0.6 - it served the gzip file instead of the brotli one. Using orderPreference resolved the issue, but it sounds like that's a regression?

**Comment by tkoenig89** [comment]
Hi @charliematters,

as `express-static-gzip` takes the order provided by the browser's 'Accept-Encoding' header into account (if you don't overwrite it with `orderPreference`), this is the expected behaviour. There are also unit tests in place to ensure, that the selection of encoding is handled properly. 

If you are still seeing a bug in this, feel free to provide an additional (failing) unit test, so we can implement a fix.

**Comment by charliematters** [comment]
Interesting - thanks!

I wonder why chrome would prefer gzip over brotli! Anyway, I'll check tomorrow on the header order.

Edit: Yep, Chrome is requesting `gzip deflate br` so I'm going to use the `orderPreference`. Sorry for digging this up!
