### ISSUE TITLE
Awesome lib. Thanks!

### ISSUE THREAD

**Issue by nodkz** [tkoenig89/express-static-gzip#8]
Just now read https://medium.com/@rajaraodv/two-quick-ways-to-reduce-react-apps-size-in-production-82226605771a#.9woyhpj4o

And saw that in step 4 it has no check `Accept-Encoding`:
```
4. Finally, add this middleware to Express to return .js.gz so you can still load bundle.js from the html but will receive bundle.js.gz
app.get('*.js', function (req, res, next) {
  req.url = req.url + '.gz';
  res.set('Content-Encoding', 'gzip');
  next();
});
```

After 5 min of googling I found your awesome lib. Exactly what is needed! Thanks!

**Comment by tkoenig89** [comment]
Glad i could help :) Was looking for something like this myself y few months ago, and because I did not find anything decided to write it myself.

Let me know if you have any extensions of functionality you might need, and as long as it won't blow up the scope of this small middleware I might add it. Or feel free to provide a pull request.

Regards,
Tobi
