### ISSUE TITLE
Need to restart server after new gzipped files have been added to public folder

### ISSUE THREAD

**Issue by tylergraf** [tkoenig89/express-static-gzip#9]
I've noticed that when I run my `gulp` task to zip the files into the public folder, I have to restart my server because it doesn't pick up the new files. Can this be fixed?

**Comment by tkoenig89** [comment]
This is totally intentional, as scanning the folder for new files each time a file is requested would kill performance for a single request. This is why files are only scanned during initialization of the middleware.

At the moment I'm not sure how to integrate such an updating feature. Maybe a function that is somehow publicly accessible and triggers the middleware to update it's file registry. Maybe a filewatcher to check for changes in the static folder, but this seems to me more like a feature used in development only.

If you could provide a more detailed use case or even a pull request i might consider adding such a feature.

**Comment by tylergraf** [comment]
Yeah, I would only expect this feature to be used in development. Maybe I'm an edge case, I can still work around this issue by restarting my server for now.
